### ISSUE TITLE
Ref propType

### ISSUE THREAD

**Issue by codesignist** [aholachek/react-stripe-menu#4]
This line:
https://github.com/aholachek/react-stripe-menu/blob/b9ecf1c4d2ff67cfa297221552a5f903efa3edf8/src/DropdownContainer/FadeContents.js#L28

Throws this error:

> Warning: [object Object]: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

https://reactjs.org/warnings/special-props.html

**Comment by aholachek** [comment]
Thank you for pointing this out! I just removed it.
