### ISSUE TITLE
Text anti-aliasing

### ISSUE THREAD

**Issue by codesignist** [aholachek/react-stripe-menu#5]
While on move texts are shaking. But, on stripe website menu texts seem very smooth.
Is this problem occurring because of anti-aliasing?

On stripe website they have used these styles:
```CSS
-webkit-text-size-adjust: 100%;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
text-rendering: optimizeLegibility;
-webkit-font-feature-settings: "pnum";
font-feature-settings: "pnum";
font-variant-numeric: proportional-nums
```

**Comment by aholachek** [comment]
Hi, thanks for pointing this out. 
I think the issue stems from how  some browser / screen combinations handle the `scale` transform more so than the text aliasing. Your issue made me [experiment with `will-change:transform` on the relevant elements](https://github.com/aholachek/react-stripe-menu/blob/master/src/DropdownContainer/utils.js)  and I think it does help a lot on Chrome and Safari, although there is still a jitter in Firefox. [Could you check out the updated version](https://alex.holachek.com/react-stripe-menu/) and let me know if it looks any better to you?

**Comment by codesignist** [comment]
Hi,
Updated version looks very good.
I applied your changes to my project, but unfortunately my menu is still shaking.
(I'm testing on Chrome 76)
